/** Latimer Park contractor sign-in. TEST mode until explicitly enabled. */
const CFG = Object.freeze({sheetId:'1u53ARXf_uwRlpg4rm0dHsU6-fIDaS42IUoHScNN6CVU',formId:'1a_q2c_o70Xmtn1wqz9j5xVq-Ct8EGjXZAiHoZ6FK7ys',site:'Latimer Park',zone:'Europe/London',version:'2026-09-26-v1',live:false});
/* [question, correct answer, wrong answers]. The phone shuffles the options; only the server knows which is correct. */
const QUIZ = [
 ['What colour are the internal and external pedestrian walkways?', 'Yellow', ['Green', 'White', 'Blue']],
 ['What is the site speed limit around the perimeter of the warehouse?', '10 mph', ['5 mph', '15 mph', '20 mph']],
 ['Alongside high-visibility clothing, what PPE is mandatory across the site?', 'Safety footwear', ['Hard hat', 'Safety glasses', 'Gloves']],
 ['How many tones does the fire alarm contain?', 'Two tones', ['One tone', 'Three tones', 'Four tones']],
 ['How many tones does the ammonia alarm contain?', 'One tone', ['Two tones', 'Three tones', 'Four tones']],
 ['Where can you retrieve keys for locked areas of the building?', 'Site security', ['Reception', 'Transport office', 'Any warehouse manager']],
 ['In addition to RAMS, signing in and induction, what process is needed before work starts?', 'Permit to work', ['Toolbox talk', 'Site tour', 'Vehicle check']]
];
const SURVEY='Survey - No Works (Pen and Paper Exercise / Measuring for Quote)';
const WORK='Maintenance Works or Surveys Behind Locked Areas';
const DECLARATION='Yes - I Confirm I have fully understood the Site Induction.';
const LOG='Contractor / Visitor Log';
const INDUCTION_HEADERS=['Completion ID','Site','Full name','Company','Contact number','Identity key','Completed at','Renewal date','Material version','Declaration','Quiz answers'];
function doGet(){return HtmlService.createHtmlOutputFromFile('Index').setTitle('Latimer Park | Sign in and out').addMetaTag('viewport','width=device-width, initial-scale=1');}
function tidy_(v,max){const s=String(v==null?'':v).trim().replace(/\s+/g,' ');if(!s||s.length>(max||160))throw Error('Please complete all required fields.');return s;}
function phone_(v){let p=String(v||'').replace(/[\s().-]/g,'');if(p.startsWith('0044'))p='0'+p.slice(4);else if(p.startsWith('+44'))p='0'+p.slice(3);if(!/^(0[1-9]\d{8,9}|\+[1-9]\d{7,14})$/.test(p)||/^(\d)\1+$/.test(p))throw Error('Enter your own valid contact number, including country code for a non-UK number.');return p;}
function identity_(p){const name=tidy_(p.name,120);if(name.split(' ').length<2)throw Error('Enter your first name and surname.');const phone=phone_(p.phone);return {name,phone,company:tidy_(p.company,120),key:name.normalize('NFKC').toLowerCase()+'|'+phone};}
function safe_(v){return typeof v==='string'&&/^[=+@\-]/.test(v)?"'"+v:v;}
function day_(date){const d=Utilities.formatDate(date,CFG.zone,'yyyy-MM-dd');return Math.floor(Date.parse(d+'T00:00:00Z')/86400000);}
function isoDay_(n){return new Date(n*86400000).toISOString().slice(0,10);}
function validAge_(completedDay,visitDay){return Number.isInteger(completedDay)&&completedDay<=visitDay&&visitDay<completedDay+365;}
function answers_(a){if(!Array.isArray(a)||a.length!==QUIZ.length)return QUIZ.map((_,i)=>i+1);return QUIZ.reduce((bad,q,i)=>{if(a[i]!==q[1])bad.push(i+1);return bad;},[]);}
function book_(){return SpreadsheetApp.openById(CFG.sheetId);}
function names_(){return CFG.live?{attendance:'App Responses',induction:'App Inductions',receipts:'App Receipts'}:{attendance:'App Test Attendance',induction:'App Test Inductions',receipts:'App Test Receipts'};}
function source_(){const form=FormApp.openById(CFG.formId);let inside=false;const images=[];for(const item of form.getItems()){if(item.getType()===FormApp.ItemType.PAGE_BREAK){inside=item.getTitle()==='Site Induction - There Will Be a Short Quiz Afterwards';}else if(inside&&item.getType()===FormApp.ItemType.IMAGE){images.push(item.asImageItem());}}if(!images.length)throw Error('The induction material is unavailable. Please try again later.');return images;}
function tab_(name){const s=book_().getSheetByName(name);if(!s)throw Error('The app has not been set up yet. Please contact the site.');return s;}
function rows_(s,n){return s.getLastRow()<2?[]:s.getRange(2,1,s.getLastRow()-1,n).getValues();}
function append_(s,row){const next=s.getLastRow()+1;if(next>s.getMaxRows())s.insertRowsAfter(s.getMaxRows(),100);s.getRange(next,1,1,row.length).setValues([row.map(safe_)]);SpreadsheetApp.flush();return next;}
/* Creates the app's tabs for the current mode. The app never writes into the Form's own response tab; its rows go to a tab with identical columns. */
function setup(){const b=book_(),source=b.getSheetByName(LOG);if(!source)throw Error('Attendance source not found.');const headers=source.getRange(1,1,1,22).getValues()[0];if(headers[0]!=='Timestamp'||headers[1]!=='Are you Signing In or Out?'||headers[4]!=='Contact Number'||headers[21]!=='Full Name')throw Error('Attendance columns have changed.');const defs=[[names_().attendance,headers],[names_().induction,INDUCTION_HEADERS],[names_().receipts,['Request ID','Created at','Identity key','Result']]];for(const [name,h] of defs){let s=b.getSheetByName(name);if(!s){s=b.insertSheet(name);s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1);s.getRange(1,1,1,h.length).setFontWeight('bold').setBackground('#145743').setFontColor('#ffffff');s.autoResizeColumns(1,h.length);}}const a=tab_(names_().attendance);a.getRange('A:A').setNumberFormat('dd/MM/yyyy HH:mm:ss');a.getRange('E:E').setNumberFormat('@');const i=tab_(names_().induction);i.getRange('E:E').setNumberFormat('@');i.getRange('G:G').setNumberFormat('dd/MM/yyyy HH:mm:ss');return {mode:CFG.live?'LIVE':'TEST',slides:source_().length,checks:runChecks()};}
/* Points the register's Data tab at the Form log and the app tab together, so Sign In / Out, Induction Register and the evacuation count include app sign-ins. FILTER is used rather than QUERY because QUERY blanks values whose type differs from the rest of the column (e.g. phone numbers stored as numbers). The previous formula is kept in a note on Data!A1. */
function linkRegister(){if(!CFG.live)throw Error('Link the register only in live mode, so test entries stay out of it.');const data=book_().getSheetByName('Data');if(!data)throw Error('Data tab not found.');tab_(names_().attendance);const log="'"+LOG+"'",app="'"+names_().attendance+"'",cell=data.getRange('A1'),old=cell.getFormula();if(old.includes(app))return 'Already linked.';cell.setNote('Formula before the app was linked:\n'+old);cell.setFormula('={'+log+'!A1:V1;SORT(FILTER({'+log+'!A2:V;'+app+'!A2:V},{'+log+'!A2:A;'+app+'!A2:A}<>""),1,TRUE)}');SpreadsheetApp.flush();return 'Linked: Data now combines '+LOG+' and '+names_().attendance+'.';}
function config(){return {site:CFG.site,test:!CFG.live,questions:QUIZ.map(x=>({text:x[0],options:[x[1],...x[2]]})),survey:SURVEY,work:WORK};}
function session_(token){if(typeof token!=='string'||!/^[a-f0-9-]{36}$/.test(token))throw Error('Please start again.');const raw=CacheService.getScriptCache().get('session:'+token);if(!raw)throw Error('Your session expired. Please start again.');const s=JSON.parse(raw);if(s.version!==CFG.version||s.live!==CFG.live)throw Error('The app was updated. Please start again.');return s;}
function saveSession_(token,s){CacheService.getScriptCache().put('session:'+token,JSON.stringify(s),3600);}
function currentInduction_(key,now){const today=day_(now);return rows_(tab_(names_().induction),11).reverse().find(r=>r[1]===CFG.site&&r[5]===key&&r[8]===CFG.version&&r[9]===true&&r[6] instanceof Date&&validAge_(day_(r[6]),today));}
function begin(p){const id=identity_(p);if(!['Sign In','Sign Out'].includes(p.action))throw Error('Choose sign in or sign out.');tab_(names_().attendance);const s={...id,action:p.action,version:CFG.version,live:CFG.live,seen:[],attempts:0,created:Date.now(),fresh:false};const token=Utilities.getUuid();let required=false;if(p.action==='Sign In')required=!currentInduction_(id.key,new Date());const known=rows_(tab_(names_().induction),11).reverse().find(r=>r[1]===CFG.site&&r[5]===id.key);if(known)s.name=String(known[2]);s.required=required;s.slides=required?source_().length:0;saveSession_(token,s);return {token,required,slides:s.slides};}
/* All pages are delivered together so the induction scrolls like one document; the client unlocks the quiz only after every page has been scrolled to its end. */
function material(token){const s=session_(token);if(!s.required)throw Error('Invalid material request.');const images=source_();if(images.length!==s.slides)throw Error('The induction has changed. Please start again.');const pages=images.map((img,i)=>{const blob=img.getImage();return {title:img.getTitle()||'Induction page '+(i+1),description:img.getHelpText()||'',data:'data:'+blob.getContentType()+';base64,'+Utilities.base64Encode(blob.getBytes())};});s.seen=pages.map((_,i)=>i);saveSession_(token,s);return pages;}
function completeInduction(token,answers,declared){const lock=LockService.getScriptLock();lock.waitLock(20000);try{const s=session_(token);if(s.fresh)return {ok:true};if(!s.required||declared!==true||s.seen.length!==s.slides)throw Error('Read every induction page and confirm the declaration first.');s.attempts++;if(s.attempts>10)throw Error('Please restart the induction and review the material.');saveSession_(token,s);const bad=answers_(answers);if(bad.length)return {ok:false,incorrect:bad};const sheet=tab_(names_().induction);const existing=rows_(sheet,11).find(r=>r[0]===token);if(!existing){const now=new Date();append_(sheet,[token,CFG.site,s.name,s.company,s.phone,s.key,now,isoDay_(day_(now)+365),CFG.version,true,JSON.stringify(answers.map(x=>tidy_(x,160)))]);}s.fresh=true;s.answers=answers;s.required=false;saveSession_(token,s);return {ok:true};}finally{lock.releaseLock();}}
function receipt_(token){const row=rows_(tab_(names_().receipts),4).find(r=>r[0]===token);return row?JSON.parse(row[3]):null;}
function visit_(p,action){const kind=tidy_(p.kind);if(!['Contractor','Visitor'].includes(kind))throw Error('Choose contractor or visitor.');if(action==='Sign Out'){const scope=kind==='Visitor'?'Visiting Only (Non Contractor)':tidy_(p.scope);if(![SURVEY,WORK,'Visiting Only (Non Contractor)'].includes(scope))throw Error('Choose the work completed.');if(scope===WORK&&(p.permitConfirmed!==true||!String(p.permitNumber||'').trim()))throw Error('Confirm permit sign-off and enter its number.');return {kind,scope,permit:scope===WORK?tidy_(p.permitNumber,60):''};}const reason=tidy_(p.reason,1000);const scope=kind==='Visitor'?'':tidy_(p.scope);if(kind==='Contractor'&&![SURVEY,WORK].includes(scope))throw Error('Choose your work type.');if(scope===WORK&&p.permitConfirmed!==true)throw Error('Confirm that you will sign on to a permit to work.');return {kind,scope,reason};}
function submitVisit(token,p){const lock=LockService.getScriptLock();lock.waitLock(20000);try{const s=session_(token),old=receipt_(token);if(old)return old;const v=visit_(p,s.action),now=new Date();if(s.action==='Sign In'&&!currentInduction_(s.key,now))throw Error('A current completed induction is required. Please start again.');const sheet=tab_(names_().attendance);const h=sheet.getRange(1,1,1,22).getValues()[0];if(h[0]!=='Timestamp'||h[4]!=='Contact Number'||h[21]!=='Full Name')throw Error('Attendance columns have changed. No record was written.');const row=Array(22).fill('');row[0]=now;row[1]=s.action;row[3]=s.company;row[4]=s.phone;if(s.action==='Sign In'){row[2]=s.name;row[5]=s.fresh?'No':'Yes';if(s.fresh){row[6]=DECLARATION;s.answers.forEach((a,i)=>row[7+i]=a);}row[14]=v.kind;row[15]=v.reason;row[16]=v.scope;row[17]=v.scope===WORK?'Yes':'';}else{row[18]=v.scope===WORK?'Maintenance Works or Surveys behind locked areas':v.scope;row[19]=v.permit;row[20]=v.scope===WORK?'Yes':'';row[21]=s.name;}/* Pending receipts make uncertain writes visible rather than silently retrying. */const receiptSheet=tab_(names_().receipts);const receiptRow=append_(receiptSheet,[token,now,s.key,JSON.stringify({ok:false,pending:true,message:'This submission needs checking before retrying. Please contact the site.'})]);append_(sheet,row);const result={ok:true,action:s.action,test:!CFG.live,message:s.action==='Sign Out'?'You are signed out.':'Your sign-in is recorded. '+(v.scope===WORK?'You must sign on to a permit to work before starting any maintenance.':v.kind==='Contractor'?'Please make yourself known to a manager in Ambient or Fresh before proceeding.':'Please report to your site contact.')};receiptSheet.getRange(receiptRow,4).setValue(JSON.stringify(result));SpreadsheetApp.flush();return result;}finally{lock.releaseLock();}}
function runChecks(){let n=0;const check=(v,m)=>{if(!v)throw Error(m);n++;};check(validAge_(100,100),'same day');check(validAge_(100,464),'day 364');check(!validAge_(100,465),'day 365 expired');check(!validAge_(101,100),'future date');check(phone_('+44 7700 900123')==='07700900123','UK normalisation');check(phone_('0044 7700 900123')==='07700900123','international prefix');check(identity_({name:' Jane  Smith ',company:'Example',phone:'07700900123'}).key==='jane smith|07700900123','identity');check(answers_(QUIZ.map(q=>q[1])).length===0,'correct answers');check(answers_(QUIZ.map((q,i)=>[1,3,4].includes(i)?q[2][0]:q[1])).join(',')==='2,4,5','wrong options rejected');check(answers_(QUIZ.map(q=>' '+q[1])).length===QUIZ.length,'only exact options accepted');check(QUIZ.every(q=>q[2].length===3&&!q[2].includes(q[1])),'quiz options');check(safe_('=IMPORTXML(1)')[0]==="'",'formula injection');check(visit_({kind:'Visitor',reason:'Meeting'},'Sign In').scope==='','visitor');let rejected=false;try{visit_({kind:'Contractor',scope:WORK,reason:'Repair'},'Sign In');}catch(e){rejected=true;}check(rejected,'permit required');console.log(n+' checks passed');return n+' checks passed';}

function formatTestTabs(){if(CFG.live)throw Error('Test sheets only.');const specs=[['App Test Attendance',[180,130,190,180,150,130,260,210,210,210,210,210,210,240,150,260,260,220,260,150,220,190]],['App Test Inductions',[280,150,190,180,150,300,180,140,150,130,400]],['App Test Receipts',[280,180,300,460]]];for(const [name,widths] of specs){const s=tab_(name);widths.forEach((w,i)=>s.setColumnWidth(i+1,w));const area=s.getRange(1,1,Math.max(2,s.getLastRow()),widths.length);area.setWrap(true).setVerticalAlignment('top');s.setRowHeight(1,name==='App Test Attendance'?120:48);if(s.getLastRow()>1)s.autoResizeRows(2,s.getLastRow()-1);s.setFrozenRows(1);}console.log('Test tab formatting updated.');}
